//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonFramework.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonFramework.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration value is invalid..
        /// </summary>
        internal static string EnumerationValueInvalid {
            get {
                return ResourceManager.GetString("EnumerationValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection has changed during enumeration..
        /// </summary>
        internal static string EnumSourceChanged {
            get {
                return ResourceManager.GetString("EnumSourceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Attributes:.
        /// </summary>
        internal static string ExceptionAttributes {
            get {
                return ResourceManager.GetString("ExceptionAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string ExceptionDetail {
            get {
                return ResourceManager.GetString("ExceptionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string ExceptionInformation {
            get {
                return ResourceManager.GetString("ExceptionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Stack:.
        /// </summary>
        internal static string ExceptionStack {
            get {
                return ResourceManager.GetString("ExceptionStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type:.
        /// </summary>
        internal static string ExceptionType {
            get {
                return ResourceManager.GetString("ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file already exists..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index cannot be found in the sources collection..
        /// </summary>
        internal static string IndexNotInSources {
            get {
                return ResourceManager.GetString("IndexNotInSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index out of bounds..
        /// </summary>
        internal static string IndexOutOfBounds {
            get {
                return ResourceManager.GetString("IndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number:.
        /// </summary>
        internal static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method:.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.a..
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File:.
        /// </summary>
        internal static string SourceFile {
            get {
                return ResourceManager.GetString("SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace:.
        /// </summary>
        internal static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrown by code in class:.
        /// </summary>
        internal static string ThrownByClass {
            get {
                return ResourceManager.GetString("ThrownByClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrown by code in method:.
        /// </summary>
        internal static string ThrownByMethod {
            get {
                return ResourceManager.GetString("ThrownByMethod", resourceCulture);
            }
        }
    }
}
